### ISSUE TITLE
Significantly slows down autocomplete even when the tab isn't focused

### ISSUE THREAD

**Issue by evelant** [mxsdev/ts-type-explorer#37]
Type: <b>Bug</b>

This extension appears to greatly slow down TS autocomplete even when the extension tab is not focused. It creates a big drag on editing speed. Hopefully the extension can be updated so that it does nothing unless it's the active panel.

Extension version: 0.4.2
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:58:33.551Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|12, 13, 16|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details>

**Comment by mxsdev** [comment]
Ah, yeah, I thought I fixed this earlier but I still need to address it!

**Comment by nrgbistro** [comment]
This is still an issue from what I can tell, vs-code becomes extremely slow for me with this extension enabled and I lose intellisense as well. Hoping this can be fixed soon because this extension is so useful to me
